alter table startups
  add column if not exists description text,
  add column if not exists website text,
  add column if not exists problem text,
  add column if not exists solution text,
  add column if not exists business_model text,
  add column if not exists use_of_funds text,
  add column if not exists tagline text,
  add column if not exists founded_year int,
  add column if not exists previous_funding text,
  add column if not exists current_investors text,
  add column if not exists market_size text,
  add column if not exists competitive_advantage text,
  add column if not exists why_now text,
  add column if not exists founder_name text,
  add column if not exists founder_email text,
  add column if not exists founder_linkedin text,
  add column if not exists cofounder_name text,
  add column if not exists cofounder_linkedin text,
  add column if not exists key_metric text,
  add column if not exists growth_rate text,
  add column if not exists customer_count text,
  add column if not exists profile_slug text,
  add column if not exists profile_published boolean default false,
  add column if not exists section_visibility jsonb default '{}'::jsonb,
  add column if not exists why_us text,
  add column if not exists tam text,
  add column if not exists sam text,
  add column if not exists target_customer text,
  add column if not exists revenue_model text,
  add column if not exists pricing text,
  add column if not exists unit_economics text,
  add column if not exists burn_rate text,
  add column if not exists runway_months int,
  add column if not exists advisors text,
  add column if not exists competitors text,
  add column if not exists milestones text,
  add column if not exists intro_video_url text,
  add column if not exists product_video_url text,
  add column if not exists moat text,
  add column if not exists logo_url text,
  add column if not exists pitch_deck_url text;

create unique index if not exists startups_profile_slug_key on startups(profile_slug);
