/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as VerifySlugRouteImport } from './routes/verify.$slug'
import { Route as ToolsValuationRouteImport } from './routes/tools/valuation'
import { Route as ToolsSafeNoteRouteImport } from './routes/tools/safe-note'
import { Route as ToolsRunwayRouteImport } from './routes/tools/runway'
import { Route as ToolsDilutionRouteImport } from './routes/tools/dilution'
import { Route as ToolsCogsRouteImport } from './routes/tools/cogs'
import { Route as ToolsCapTableRouteImport } from './routes/tools/cap-table'
import { Route as ToolsBurnRateRouteImport } from './routes/tools/burn-rate'
import { Route as SolutionsVcDealRoomRouteImport } from './routes/solutions.vc-deal-room'
import { Route as SolutionsRaise1mRouteImport } from './routes/solutions.raise-1m'
import { Route as SolutionsInvestorPipelineRouteImport } from './routes/solutions.investor-pipeline'
import { Route as SolutionsFundraisingCrmRouteImport } from './routes/solutions.fundraising-crm'
import { Route as SolutionsDueDiligenceRouteImport } from './routes/solutions.due-diligence'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as JoinInvestorTokenRouteImport } from './routes/join-investor.$token'
import { Route as ISlugRouteImport } from './routes/i.$slug'
import { Route as CvSlugRouteImport } from './routes/cv.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppWallRouteImport } from './routes/app.wall'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReferralsRouteImport } from './routes/app.referrals'
import { Route as AppProfileBuilderRouteImport } from './routes/app.profile-builder'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMemberProfileRouteImport } from './routes/app.member-profile'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppInvestorThesisRouteImport } from './routes/app.investor-thesis'
import { Route as AppInvestorRouteImport } from './routes/app.investor'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'
import { Route as AppEmailRouteImport } from './routes/app.email'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDirectoryRouteImport } from './routes/app.directory'
import { Route as AppDeskRouteImport } from './routes/app.desk'
import { Route as AppDealRoomsRouteImport } from './routes/app.deal-rooms'
import { Route as AppConnectionsRouteImport } from './routes/app.connections'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAdvisorRouteImport } from './routes/app.advisor'
import { Route as ApiTestAiRouteImport } from './routes/api.test-ai'
import { Route as ApiHubspotSyncRouteImport } from './routes/api.hubspot-sync'
import { Route as ApiHubspotNewsletterRouteImport } from './routes/api.hubspot-newsletter'
import { Route as ApiEmailtestRouteImport } from './routes/api.emailtest'
import { Route as ApiEmailTestRouteImport } from './routes/api.email-test'
import { Route as ApiAdminDataRouteImport } from './routes/api.admin-data'
import { Route as ApiAdminRouteImport } from './routes/api.admin'
import { Route as AppMemberIndexRouteImport } from './routes/app.member.index'
import { Route as AppInvestorIndexRouteImport } from './routes/app.investor.index'
import { Route as JoinTeamTokenRouteImport } from './routes/join.team.$token'
import { Route as AppSettingsSecurityRouteImport } from './routes/app.settings.security'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppSettingsDomainRouteImport } from './routes/app.settings.domain'
import { Route as AppSettingsBillingRouteImport } from './routes/app.settings.billing'
import { Route as AppInvestorTeamRouteImport } from './routes/app.investor.team'
import { Route as AppInvestorStartupsRouteImport } from './routes/app.investor.startups'
import { Route as AppInvestorSettingsRouteImport } from './routes/app.investor.settings'
import { Route as AppInvestorProfileRouteImport } from './routes/app.investor.profile'
import { Route as AppInvestorPortfolioRouteImport } from './routes/app.investor.portfolio'
import { Route as AppInvestorPipelineRouteImport } from './routes/app.investor.pipeline'
import { Route as AppInvestorOverviewRouteImport } from './routes/app.investor.overview'
import { Route as AppInvestorIntakeRouteImport } from './routes/app.investor.intake'
import { Route as AppInvestorDiligenceRouteImport } from './routes/app.investor.diligence'
import { Route as AppInvestorDeskRouteImport } from './routes/app.investor.desk'
import { Route as AppInvestorDecisionsRouteImport } from './routes/app.investor.decisions'
import { Route as AppInvestorDealRoomsRouteImport } from './routes/app.investor.deal-rooms'
import { Route as AppInvestorDealFlowRouteImport } from './routes/app.investor.deal-flow'
import { Route as AppInvestorConnectionsRouteImport } from './routes/app.investor.connections'
import { Route as AppInvestorAnalysisRouteImport } from './routes/app.investor.analysis'
import { Route as AppInvestorAdvisorRouteImport } from './routes/app.investor.advisor'
import { Route as AppDealRoomIdRouteImport } from './routes/app.deal-room.$id'
import { Route as ApiInternalEmailTestRouteImport } from './routes/api.internal.email-test'
import { Route as ApiInternalDataRouteImport } from './routes/api.internal.data'
import { Route as AppDealRoomIdNdaRouteImport } from './routes/app.deal-room.$id_.nda'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VerifySlugRoute = VerifySlugRouteImport.update({
  id: '/verify/$slug',
  path: '/verify/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsValuationRoute = ToolsValuationRouteImport.update({
  id: '/tools/valuation',
  path: '/tools/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSafeNoteRoute = ToolsSafeNoteRouteImport.update({
  id: '/tools/safe-note',
  path: '/tools/safe-note',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRunwayRoute = ToolsRunwayRouteImport.update({
  id: '/tools/runway',
  path: '/tools/runway',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDilutionRoute = ToolsDilutionRouteImport.update({
  id: '/tools/dilution',
  path: '/tools/dilution',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCogsRoute = ToolsCogsRouteImport.update({
  id: '/tools/cogs',
  path: '/tools/cogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCapTableRoute = ToolsCapTableRouteImport.update({
  id: '/tools/cap-table',
  path: '/tools/cap-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBurnRateRoute = ToolsBurnRateRouteImport.update({
  id: '/tools/burn-rate',
  path: '/tools/burn-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsVcDealRoomRoute = SolutionsVcDealRoomRouteImport.update({
  id: '/solutions/vc-deal-room',
  path: '/solutions/vc-deal-room',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRaise1mRoute = SolutionsRaise1mRouteImport.update({
  id: '/solutions/raise-1m',
  path: '/solutions/raise-1m',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsInvestorPipelineRoute =
  SolutionsInvestorPipelineRouteImport.update({
    id: '/solutions/investor-pipeline',
    path: '/solutions/investor-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsFundraisingCrmRoute = SolutionsFundraisingCrmRouteImport.update({
  id: '/solutions/fundraising-crm',
  path: '/solutions/fundraising-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsDueDiligenceRoute = SolutionsDueDiligenceRouteImport.update({
  id: '/solutions/due-diligence',
  path: '/solutions/due-diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => JoinRoute,
} as any)
const JoinInvestorTokenRoute = JoinInvestorTokenRouteImport.update({
  id: '/join-investor/$token',
  path: '/join-investor/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ISlugRoute = ISlugRouteImport.update({
  id: '/i/$slug',
  path: '/i/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CvSlugRoute = CvSlugRouteImport.update({
  id: '/cv/$slug',
  path: '/cv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWallRoute = AppWallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileBuilderRoute = AppProfileBuilderRouteImport.update({
  id: '/profile-builder',
  path: '/profile-builder',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMemberProfileRoute = AppMemberProfileRouteImport.update({
  id: '/member-profile',
  path: '/member-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorThesisRoute = AppInvestorThesisRouteImport.update({
  id: '/investor-thesis',
  path: '/investor-thesis',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorRoute = AppInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppDeskRoute = AppDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AppRoute,
} as any)
const AppDealRoomsRoute = AppDealRoomsRouteImport.update({
  id: '/deal-rooms',
  path: '/deal-rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const ApiTestAiRoute = ApiTestAiRouteImport.update({
  id: '/api/test-ai',
  path: '/api/test-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHubspotSyncRoute = ApiHubspotSyncRouteImport.update({
  id: '/api/hubspot-sync',
  path: '/api/hubspot-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHubspotNewsletterRoute = ApiHubspotNewsletterRouteImport.update({
  id: '/api/hubspot-newsletter',
  path: '/api/hubspot-newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailtestRoute = ApiEmailtestRouteImport.update({
  id: '/api/emailtest',
  path: '/api/emailtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailTestRoute = ApiEmailTestRouteImport.update({
  id: '/api/email-test',
  path: '/api/email-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDataRoute = ApiAdminDataRouteImport.update({
  id: '/api/admin-data',
  path: '/api/admin-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMemberIndexRoute = AppMemberIndexRouteImport.update({
  id: '/member/',
  path: '/member/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorIndexRoute = AppInvestorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvestorRoute,
} as any)
const JoinTeamTokenRoute = JoinTeamTokenRouteImport.update({
  id: '/team/$token',
  path: '/team/$token',
  getParentRoute: () => JoinRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsDomainRoute = AppSettingsDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInvestorTeamRoute = AppInvestorTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorStartupsRoute = AppInvestorStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorSettingsRoute = AppInvestorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorProfileRoute = AppInvestorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorPortfolioRoute = AppInvestorPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorPipelineRoute = AppInvestorPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorOverviewRoute = AppInvestorOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorIntakeRoute = AppInvestorIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorDiligenceRoute = AppInvestorDiligenceRouteImport.update({
  id: '/diligence',
  path: '/diligence',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorDeskRoute = AppInvestorDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorDecisionsRoute = AppInvestorDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorDealRoomsRoute = AppInvestorDealRoomsRouteImport.update({
  id: '/deal-rooms',
  path: '/deal-rooms',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorDealFlowRoute = AppInvestorDealFlowRouteImport.update({
  id: '/deal-flow',
  path: '/deal-flow',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorConnectionsRoute = AppInvestorConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorAnalysisRoute = AppInvestorAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppInvestorAdvisorRoute = AppInvestorAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppInvestorRoute,
} as any)
const AppDealRoomIdRoute = AppDealRoomIdRouteImport.update({
  id: '/deal-room/$id',
  path: '/deal-room/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiInternalEmailTestRoute = ApiInternalEmailTestRouteImport.update({
  id: '/api/internal/email-test',
  path: '/api/internal/email-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalDataRoute = ApiInternalDataRouteImport.update({
  id: '/api/internal/data',
  path: '/api/internal/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDealRoomIdNdaRoute = AppDealRoomIdNdaRouteImport.update({
  id: '/deal-room/$id_/nda',
  path: '/deal-room/$id/nda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/debug': typeof DebugRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registry': typeof RegistryRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/waitlist': typeof WaitlistRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-data': typeof ApiAdminDataRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/api/emailtest': typeof ApiEmailtestRoute
  '/api/hubspot-newsletter': typeof ApiHubspotNewsletterRoute
  '/api/hubspot-sync': typeof ApiHubspotSyncRoute
  '/api/test-ai': typeof ApiTestAiRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/audit': typeof AppAuditRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/deal-rooms': typeof AppDealRoomsRoute
  '/app/desk': typeof AppDeskRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/home': typeof AppHomeRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/investor': typeof AppInvestorRouteWithChildren
  '/app/investor-thesis': typeof AppInvestorThesisRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/member-profile': typeof AppMemberProfileRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/profile-builder': typeof AppProfileBuilderRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/wall': typeof AppWallRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cv/$slug': typeof CvSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/join-investor/$token': typeof JoinInvestorTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/solutions/due-diligence': typeof SolutionsDueDiligenceRoute
  '/solutions/fundraising-crm': typeof SolutionsFundraisingCrmRoute
  '/solutions/investor-pipeline': typeof SolutionsInvestorPipelineRoute
  '/solutions/raise-1m': typeof SolutionsRaise1mRoute
  '/solutions/vc-deal-room': typeof SolutionsVcDealRoomRoute
  '/tools/burn-rate': typeof ToolsBurnRateRoute
  '/tools/cap-table': typeof ToolsCapTableRoute
  '/tools/cogs': typeof ToolsCogsRoute
  '/tools/dilution': typeof ToolsDilutionRoute
  '/tools/runway': typeof ToolsRunwayRoute
  '/tools/safe-note': typeof ToolsSafeNoteRoute
  '/tools/valuation': typeof ToolsValuationRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/internal/data': typeof ApiInternalDataRoute
  '/api/internal/email-test': typeof ApiInternalEmailTestRoute
  '/app/deal-room/$id': typeof AppDealRoomIdRoute
  '/app/investor/advisor': typeof AppInvestorAdvisorRoute
  '/app/investor/analysis': typeof AppInvestorAnalysisRoute
  '/app/investor/connections': typeof AppInvestorConnectionsRoute
  '/app/investor/deal-flow': typeof AppInvestorDealFlowRoute
  '/app/investor/deal-rooms': typeof AppInvestorDealRoomsRoute
  '/app/investor/decisions': typeof AppInvestorDecisionsRoute
  '/app/investor/desk': typeof AppInvestorDeskRoute
  '/app/investor/diligence': typeof AppInvestorDiligenceRoute
  '/app/investor/intake': typeof AppInvestorIntakeRoute
  '/app/investor/overview': typeof AppInvestorOverviewRoute
  '/app/investor/pipeline': typeof AppInvestorPipelineRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/settings': typeof AppInvestorSettingsRoute
  '/app/investor/startups': typeof AppInvestorStartupsRoute
  '/app/investor/team': typeof AppInvestorTeamRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/domain': typeof AppSettingsDomainRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/join/team/$token': typeof JoinTeamTokenRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/member/': typeof AppMemberIndexRoute
  '/app/deal-room/$id/nda': typeof AppDealRoomIdNdaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/debug': typeof DebugRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registry': typeof RegistryRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/waitlist': typeof WaitlistRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-data': typeof ApiAdminDataRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/api/emailtest': typeof ApiEmailtestRoute
  '/api/hubspot-newsletter': typeof ApiHubspotNewsletterRoute
  '/api/hubspot-sync': typeof ApiHubspotSyncRoute
  '/api/test-ai': typeof ApiTestAiRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/audit': typeof AppAuditRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/deal-rooms': typeof AppDealRoomsRoute
  '/app/desk': typeof AppDeskRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/home': typeof AppHomeRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/investor-thesis': typeof AppInvestorThesisRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/member-profile': typeof AppMemberProfileRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/profile-builder': typeof AppProfileBuilderRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/wall': typeof AppWallRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cv/$slug': typeof CvSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/join-investor/$token': typeof JoinInvestorTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/solutions/due-diligence': typeof SolutionsDueDiligenceRoute
  '/solutions/fundraising-crm': typeof SolutionsFundraisingCrmRoute
  '/solutions/investor-pipeline': typeof SolutionsInvestorPipelineRoute
  '/solutions/raise-1m': typeof SolutionsRaise1mRoute
  '/solutions/vc-deal-room': typeof SolutionsVcDealRoomRoute
  '/tools/burn-rate': typeof ToolsBurnRateRoute
  '/tools/cap-table': typeof ToolsCapTableRoute
  '/tools/cogs': typeof ToolsCogsRoute
  '/tools/dilution': typeof ToolsDilutionRoute
  '/tools/runway': typeof ToolsRunwayRoute
  '/tools/safe-note': typeof ToolsSafeNoteRoute
  '/tools/valuation': typeof ToolsValuationRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/api/internal/data': typeof ApiInternalDataRoute
  '/api/internal/email-test': typeof ApiInternalEmailTestRoute
  '/app/deal-room/$id': typeof AppDealRoomIdRoute
  '/app/investor/advisor': typeof AppInvestorAdvisorRoute
  '/app/investor/analysis': typeof AppInvestorAnalysisRoute
  '/app/investor/connections': typeof AppInvestorConnectionsRoute
  '/app/investor/deal-flow': typeof AppInvestorDealFlowRoute
  '/app/investor/deal-rooms': typeof AppInvestorDealRoomsRoute
  '/app/investor/decisions': typeof AppInvestorDecisionsRoute
  '/app/investor/desk': typeof AppInvestorDeskRoute
  '/app/investor/diligence': typeof AppInvestorDiligenceRoute
  '/app/investor/intake': typeof AppInvestorIntakeRoute
  '/app/investor/overview': typeof AppInvestorOverviewRoute
  '/app/investor/pipeline': typeof AppInvestorPipelineRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/settings': typeof AppInvestorSettingsRoute
  '/app/investor/startups': typeof AppInvestorStartupsRoute
  '/app/investor/team': typeof AppInvestorTeamRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/domain': typeof AppSettingsDomainRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/join/team/$token': typeof JoinTeamTokenRoute
  '/app/investor': typeof AppInvestorIndexRoute
  '/app/member': typeof AppMemberIndexRoute
  '/app/deal-room/$id/nda': typeof AppDealRoomIdNdaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/debug': typeof DebugRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registry': typeof RegistryRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/waitlist': typeof WaitlistRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/admin-data': typeof ApiAdminDataRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/api/emailtest': typeof ApiEmailtestRoute
  '/api/hubspot-newsletter': typeof ApiHubspotNewsletterRoute
  '/api/hubspot-sync': typeof ApiHubspotSyncRoute
  '/api/test-ai': typeof ApiTestAiRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/audit': typeof AppAuditRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/deal-rooms': typeof AppDealRoomsRoute
  '/app/desk': typeof AppDeskRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/home': typeof AppHomeRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/investor': typeof AppInvestorRouteWithChildren
  '/app/investor-thesis': typeof AppInvestorThesisRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/member-profile': typeof AppMemberProfileRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/profile-builder': typeof AppProfileBuilderRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/wall': typeof AppWallRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cv/$slug': typeof CvSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/join-investor/$token': typeof JoinInvestorTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/solutions/due-diligence': typeof SolutionsDueDiligenceRoute
  '/solutions/fundraising-crm': typeof SolutionsFundraisingCrmRoute
  '/solutions/investor-pipeline': typeof SolutionsInvestorPipelineRoute
  '/solutions/raise-1m': typeof SolutionsRaise1mRoute
  '/solutions/vc-deal-room': typeof SolutionsVcDealRoomRoute
  '/tools/burn-rate': typeof ToolsBurnRateRoute
  '/tools/cap-table': typeof ToolsCapTableRoute
  '/tools/cogs': typeof ToolsCogsRoute
  '/tools/dilution': typeof ToolsDilutionRoute
  '/tools/runway': typeof ToolsRunwayRoute
  '/tools/safe-note': typeof ToolsSafeNoteRoute
  '/tools/valuation': typeof ToolsValuationRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/internal/data': typeof ApiInternalDataRoute
  '/api/internal/email-test': typeof ApiInternalEmailTestRoute
  '/app/deal-room/$id': typeof AppDealRoomIdRoute
  '/app/investor/advisor': typeof AppInvestorAdvisorRoute
  '/app/investor/analysis': typeof AppInvestorAnalysisRoute
  '/app/investor/connections': typeof AppInvestorConnectionsRoute
  '/app/investor/deal-flow': typeof AppInvestorDealFlowRoute
  '/app/investor/deal-rooms': typeof AppInvestorDealRoomsRoute
  '/app/investor/decisions': typeof AppInvestorDecisionsRoute
  '/app/investor/desk': typeof AppInvestorDeskRoute
  '/app/investor/diligence': typeof AppInvestorDiligenceRoute
  '/app/investor/intake': typeof AppInvestorIntakeRoute
  '/app/investor/overview': typeof AppInvestorOverviewRoute
  '/app/investor/pipeline': typeof AppInvestorPipelineRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/settings': typeof AppInvestorSettingsRoute
  '/app/investor/startups': typeof AppInvestorStartupsRoute
  '/app/investor/team': typeof AppInvestorTeamRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/domain': typeof AppSettingsDomainRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/join/team/$token': typeof JoinTeamTokenRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/member/': typeof AppMemberIndexRoute
  '/app/deal-room/$id_/nda': typeof AppDealRoomIdNdaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/blog'
    | '/contact'
    | '/debug'
    | '/feedback'
    | '/forgot-password'
    | '/founders'
    | '/investors'
    | '/invite'
    | '/join'
    | '/pricing'
    | '/privacy'
    | '/registry'
    | '/resources'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/trust'
    | '/waitlist'
    | '/api/admin'
    | '/api/admin-data'
    | '/api/email-test'
    | '/api/emailtest'
    | '/api/hubspot-newsletter'
    | '/api/hubspot-sync'
    | '/api/test-ai'
    | '/app/advisor'
    | '/app/audit'
    | '/app/connections'
    | '/app/deal-rooms'
    | '/app/desk'
    | '/app/directory'
    | '/app/documents'
    | '/app/email'
    | '/app/feedback'
    | '/app/home'
    | '/app/integrations'
    | '/app/investor'
    | '/app/investor-thesis'
    | '/app/meetings'
    | '/app/member-profile'
    | '/app/messages'
    | '/app/notifications'
    | '/app/overview'
    | '/app/profile'
    | '/app/profile-builder'
    | '/app/referrals'
    | '/app/settings'
    | '/app/users'
    | '/app/wall'
    | '/auth/callback'
    | '/blog/$slug'
    | '/cv/$slug'
    | '/i/$slug'
    | '/join-investor/$token'
    | '/join/$token'
    | '/p/$slug'
    | '/solutions/due-diligence'
    | '/solutions/fundraising-crm'
    | '/solutions/investor-pipeline'
    | '/solutions/raise-1m'
    | '/solutions/vc-deal-room'
    | '/tools/burn-rate'
    | '/tools/cap-table'
    | '/tools/cogs'
    | '/tools/dilution'
    | '/tools/runway'
    | '/tools/safe-note'
    | '/tools/valuation'
    | '/verify/$slug'
    | '/app/'
    | '/blog/'
    | '/tools/'
    | '/api/internal/data'
    | '/api/internal/email-test'
    | '/app/deal-room/$id'
    | '/app/investor/advisor'
    | '/app/investor/analysis'
    | '/app/investor/connections'
    | '/app/investor/deal-flow'
    | '/app/investor/deal-rooms'
    | '/app/investor/decisions'
    | '/app/investor/desk'
    | '/app/investor/diligence'
    | '/app/investor/intake'
    | '/app/investor/overview'
    | '/app/investor/pipeline'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/settings'
    | '/app/investor/startups'
    | '/app/investor/team'
    | '/app/settings/billing'
    | '/app/settings/domain'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/join/team/$token'
    | '/app/investor/'
    | '/app/member/'
    | '/app/deal-room/$id/nda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/debug'
    | '/feedback'
    | '/forgot-password'
    | '/founders'
    | '/investors'
    | '/invite'
    | '/join'
    | '/pricing'
    | '/privacy'
    | '/registry'
    | '/resources'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/trust'
    | '/waitlist'
    | '/api/admin'
    | '/api/admin-data'
    | '/api/email-test'
    | '/api/emailtest'
    | '/api/hubspot-newsletter'
    | '/api/hubspot-sync'
    | '/api/test-ai'
    | '/app/advisor'
    | '/app/audit'
    | '/app/connections'
    | '/app/deal-rooms'
    | '/app/desk'
    | '/app/directory'
    | '/app/documents'
    | '/app/email'
    | '/app/feedback'
    | '/app/home'
    | '/app/integrations'
    | '/app/investor-thesis'
    | '/app/meetings'
    | '/app/member-profile'
    | '/app/messages'
    | '/app/notifications'
    | '/app/overview'
    | '/app/profile'
    | '/app/profile-builder'
    | '/app/referrals'
    | '/app/settings'
    | '/app/users'
    | '/app/wall'
    | '/auth/callback'
    | '/blog/$slug'
    | '/cv/$slug'
    | '/i/$slug'
    | '/join-investor/$token'
    | '/join/$token'
    | '/p/$slug'
    | '/solutions/due-diligence'
    | '/solutions/fundraising-crm'
    | '/solutions/investor-pipeline'
    | '/solutions/raise-1m'
    | '/solutions/vc-deal-room'
    | '/tools/burn-rate'
    | '/tools/cap-table'
    | '/tools/cogs'
    | '/tools/dilution'
    | '/tools/runway'
    | '/tools/safe-note'
    | '/tools/valuation'
    | '/verify/$slug'
    | '/app'
    | '/blog'
    | '/tools'
    | '/api/internal/data'
    | '/api/internal/email-test'
    | '/app/deal-room/$id'
    | '/app/investor/advisor'
    | '/app/investor/analysis'
    | '/app/investor/connections'
    | '/app/investor/deal-flow'
    | '/app/investor/deal-rooms'
    | '/app/investor/decisions'
    | '/app/investor/desk'
    | '/app/investor/diligence'
    | '/app/investor/intake'
    | '/app/investor/overview'
    | '/app/investor/pipeline'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/settings'
    | '/app/investor/startups'
    | '/app/investor/team'
    | '/app/settings/billing'
    | '/app/settings/domain'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/join/team/$token'
    | '/app/investor'
    | '/app/member'
    | '/app/deal-room/$id/nda'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/blog'
    | '/contact'
    | '/debug'
    | '/feedback'
    | '/forgot-password'
    | '/founders'
    | '/investors'
    | '/invite'
    | '/join'
    | '/pricing'
    | '/privacy'
    | '/registry'
    | '/resources'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/trust'
    | '/waitlist'
    | '/api/admin'
    | '/api/admin-data'
    | '/api/email-test'
    | '/api/emailtest'
    | '/api/hubspot-newsletter'
    | '/api/hubspot-sync'
    | '/api/test-ai'
    | '/app/advisor'
    | '/app/audit'
    | '/app/connections'
    | '/app/deal-rooms'
    | '/app/desk'
    | '/app/directory'
    | '/app/documents'
    | '/app/email'
    | '/app/feedback'
    | '/app/home'
    | '/app/integrations'
    | '/app/investor'
    | '/app/investor-thesis'
    | '/app/meetings'
    | '/app/member-profile'
    | '/app/messages'
    | '/app/notifications'
    | '/app/overview'
    | '/app/profile'
    | '/app/profile-builder'
    | '/app/referrals'
    | '/app/settings'
    | '/app/users'
    | '/app/wall'
    | '/auth/callback'
    | '/blog/$slug'
    | '/cv/$slug'
    | '/i/$slug'
    | '/join-investor/$token'
    | '/join/$token'
    | '/p/$slug'
    | '/solutions/due-diligence'
    | '/solutions/fundraising-crm'
    | '/solutions/investor-pipeline'
    | '/solutions/raise-1m'
    | '/solutions/vc-deal-room'
    | '/tools/burn-rate'
    | '/tools/cap-table'
    | '/tools/cogs'
    | '/tools/dilution'
    | '/tools/runway'
    | '/tools/safe-note'
    | '/tools/valuation'
    | '/verify/$slug'
    | '/app/'
    | '/blog/'
    | '/tools/'
    | '/api/internal/data'
    | '/api/internal/email-test'
    | '/app/deal-room/$id'
    | '/app/investor/advisor'
    | '/app/investor/analysis'
    | '/app/investor/connections'
    | '/app/investor/deal-flow'
    | '/app/investor/deal-rooms'
    | '/app/investor/decisions'
    | '/app/investor/desk'
    | '/app/investor/diligence'
    | '/app/investor/intake'
    | '/app/investor/overview'
    | '/app/investor/pipeline'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/settings'
    | '/app/investor/startups'
    | '/app/investor/team'
    | '/app/settings/billing'
    | '/app/settings/domain'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/join/team/$token'
    | '/app/investor/'
    | '/app/member/'
    | '/app/deal-room/$id_/nda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DebugRoute: typeof DebugRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FoundersRoute: typeof FoundersRoute
  InvestorsRoute: typeof InvestorsRoute
  InviteRoute: typeof InviteRoute
  JoinRoute: typeof JoinRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegistryRoute: typeof RegistryRoute
  ResourcesRoute: typeof ResourcesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  WaitlistRoute: typeof WaitlistRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAdminDataRoute: typeof ApiAdminDataRoute
  ApiEmailTestRoute: typeof ApiEmailTestRoute
  ApiEmailtestRoute: typeof ApiEmailtestRoute
  ApiHubspotNewsletterRoute: typeof ApiHubspotNewsletterRoute
  ApiHubspotSyncRoute: typeof ApiHubspotSyncRoute
  ApiTestAiRoute: typeof ApiTestAiRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CvSlugRoute: typeof CvSlugRoute
  ISlugRoute: typeof ISlugRoute
  JoinInvestorTokenRoute: typeof JoinInvestorTokenRoute
  PSlugRoute: typeof PSlugRoute
  SolutionsDueDiligenceRoute: typeof SolutionsDueDiligenceRoute
  SolutionsFundraisingCrmRoute: typeof SolutionsFundraisingCrmRoute
  SolutionsInvestorPipelineRoute: typeof SolutionsInvestorPipelineRoute
  SolutionsRaise1mRoute: typeof SolutionsRaise1mRoute
  SolutionsVcDealRoomRoute: typeof SolutionsVcDealRoomRoute
  ToolsBurnRateRoute: typeof ToolsBurnRateRoute
  ToolsCapTableRoute: typeof ToolsCapTableRoute
  ToolsCogsRoute: typeof ToolsCogsRoute
  ToolsDilutionRoute: typeof ToolsDilutionRoute
  ToolsRunwayRoute: typeof ToolsRunwayRoute
  ToolsSafeNoteRoute: typeof ToolsSafeNoteRoute
  ToolsValuationRoute: typeof ToolsValuationRoute
  VerifySlugRoute: typeof VerifySlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiInternalDataRoute: typeof ApiInternalDataRoute
  ApiInternalEmailTestRoute: typeof ApiInternalEmailTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/$slug': {
      id: '/verify/$slug'
      path: '/verify/$slug'
      fullPath: '/verify/$slug'
      preLoaderRoute: typeof VerifySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/valuation': {
      id: '/tools/valuation'
      path: '/tools/valuation'
      fullPath: '/tools/valuation'
      preLoaderRoute: typeof ToolsValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/safe-note': {
      id: '/tools/safe-note'
      path: '/tools/safe-note'
      fullPath: '/tools/safe-note'
      preLoaderRoute: typeof ToolsSafeNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/runway': {
      id: '/tools/runway'
      path: '/tools/runway'
      fullPath: '/tools/runway'
      preLoaderRoute: typeof ToolsRunwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/dilution': {
      id: '/tools/dilution'
      path: '/tools/dilution'
      fullPath: '/tools/dilution'
      preLoaderRoute: typeof ToolsDilutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cogs': {
      id: '/tools/cogs'
      path: '/tools/cogs'
      fullPath: '/tools/cogs'
      preLoaderRoute: typeof ToolsCogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cap-table': {
      id: '/tools/cap-table'
      path: '/tools/cap-table'
      fullPath: '/tools/cap-table'
      preLoaderRoute: typeof ToolsCapTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/burn-rate': {
      id: '/tools/burn-rate'
      path: '/tools/burn-rate'
      fullPath: '/tools/burn-rate'
      preLoaderRoute: typeof ToolsBurnRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/vc-deal-room': {
      id: '/solutions/vc-deal-room'
      path: '/solutions/vc-deal-room'
      fullPath: '/solutions/vc-deal-room'
      preLoaderRoute: typeof SolutionsVcDealRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/raise-1m': {
      id: '/solutions/raise-1m'
      path: '/solutions/raise-1m'
      fullPath: '/solutions/raise-1m'
      preLoaderRoute: typeof SolutionsRaise1mRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/investor-pipeline': {
      id: '/solutions/investor-pipeline'
      path: '/solutions/investor-pipeline'
      fullPath: '/solutions/investor-pipeline'
      preLoaderRoute: typeof SolutionsInvestorPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/fundraising-crm': {
      id: '/solutions/fundraising-crm'
      path: '/solutions/fundraising-crm'
      fullPath: '/solutions/fundraising-crm'
      preLoaderRoute: typeof SolutionsFundraisingCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/due-diligence': {
      id: '/solutions/due-diligence'
      path: '/solutions/due-diligence'
      fullPath: '/solutions/due-diligence'
      preLoaderRoute: typeof SolutionsDueDiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof JoinRoute
    }
    '/join-investor/$token': {
      id: '/join-investor/$token'
      path: '/join-investor/$token'
      fullPath: '/join-investor/$token'
      preLoaderRoute: typeof JoinInvestorTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$slug': {
      id: '/i/$slug'
      path: '/i/$slug'
      fullPath: '/i/$slug'
      preLoaderRoute: typeof ISlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$slug': {
      id: '/cv/$slug'
      path: '/cv/$slug'
      fullPath: '/cv/$slug'
      preLoaderRoute: typeof CvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wall': {
      id: '/app/wall'
      path: '/wall'
      fullPath: '/app/wall'
      preLoaderRoute: typeof AppWallRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referrals': {
      id: '/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile-builder': {
      id: '/app/profile-builder'
      path: '/profile-builder'
      fullPath: '/app/profile-builder'
      preLoaderRoute: typeof AppProfileBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/member-profile': {
      id: '/app/member-profile'
      path: '/member-profile'
      fullPath: '/app/member-profile'
      preLoaderRoute: typeof AppMemberProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor-thesis': {
      id: '/app/investor-thesis'
      path: '/investor-thesis'
      fullPath: '/app/investor-thesis'
      preLoaderRoute: typeof AppInvestorThesisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor': {
      id: '/app/investor'
      path: '/investor'
      fullPath: '/app/investor'
      preLoaderRoute: typeof AppInvestorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email': {
      id: '/app/email'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/directory': {
      id: '/app/directory'
      path: '/directory'
      fullPath: '/app/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desk': {
      id: '/app/desk'
      path: '/desk'
      fullPath: '/app/desk'
      preLoaderRoute: typeof AppDeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deal-rooms': {
      id: '/app/deal-rooms'
      path: '/deal-rooms'
      fullPath: '/app/deal-rooms'
      preLoaderRoute: typeof AppDealRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisor': {
      id: '/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/test-ai': {
      id: '/api/test-ai'
      path: '/api/test-ai'
      fullPath: '/api/test-ai'
      preLoaderRoute: typeof ApiTestAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hubspot-sync': {
      id: '/api/hubspot-sync'
      path: '/api/hubspot-sync'
      fullPath: '/api/hubspot-sync'
      preLoaderRoute: typeof ApiHubspotSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hubspot-newsletter': {
      id: '/api/hubspot-newsletter'
      path: '/api/hubspot-newsletter'
      fullPath: '/api/hubspot-newsletter'
      preLoaderRoute: typeof ApiHubspotNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emailtest': {
      id: '/api/emailtest'
      path: '/api/emailtest'
      fullPath: '/api/emailtest'
      preLoaderRoute: typeof ApiEmailtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-test': {
      id: '/api/email-test'
      path: '/api/email-test'
      fullPath: '/api/email-test'
      preLoaderRoute: typeof ApiEmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-data': {
      id: '/api/admin-data'
      path: '/api/admin-data'
      fullPath: '/api/admin-data'
      preLoaderRoute: typeof ApiAdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/member/': {
      id: '/app/member/'
      path: '/member'
      fullPath: '/app/member/'
      preLoaderRoute: typeof AppMemberIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/': {
      id: '/app/investor/'
      path: '/'
      fullPath: '/app/investor/'
      preLoaderRoute: typeof AppInvestorIndexRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/join/team/$token': {
      id: '/join/team/$token'
      path: '/team/$token'
      fullPath: '/join/team/$token'
      preLoaderRoute: typeof JoinTeamTokenRouteImport
      parentRoute: typeof JoinRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/domain': {
      id: '/app/settings/domain'
      path: '/domain'
      fullPath: '/app/settings/domain'
      preLoaderRoute: typeof AppSettingsDomainRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/investor/team': {
      id: '/app/investor/team'
      path: '/team'
      fullPath: '/app/investor/team'
      preLoaderRoute: typeof AppInvestorTeamRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/startups': {
      id: '/app/investor/startups'
      path: '/startups'
      fullPath: '/app/investor/startups'
      preLoaderRoute: typeof AppInvestorStartupsRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/settings': {
      id: '/app/investor/settings'
      path: '/settings'
      fullPath: '/app/investor/settings'
      preLoaderRoute: typeof AppInvestorSettingsRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/profile': {
      id: '/app/investor/profile'
      path: '/profile'
      fullPath: '/app/investor/profile'
      preLoaderRoute: typeof AppInvestorProfileRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/portfolio': {
      id: '/app/investor/portfolio'
      path: '/portfolio'
      fullPath: '/app/investor/portfolio'
      preLoaderRoute: typeof AppInvestorPortfolioRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/pipeline': {
      id: '/app/investor/pipeline'
      path: '/pipeline'
      fullPath: '/app/investor/pipeline'
      preLoaderRoute: typeof AppInvestorPipelineRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/overview': {
      id: '/app/investor/overview'
      path: '/overview'
      fullPath: '/app/investor/overview'
      preLoaderRoute: typeof AppInvestorOverviewRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/intake': {
      id: '/app/investor/intake'
      path: '/intake'
      fullPath: '/app/investor/intake'
      preLoaderRoute: typeof AppInvestorIntakeRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/diligence': {
      id: '/app/investor/diligence'
      path: '/diligence'
      fullPath: '/app/investor/diligence'
      preLoaderRoute: typeof AppInvestorDiligenceRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/desk': {
      id: '/app/investor/desk'
      path: '/desk'
      fullPath: '/app/investor/desk'
      preLoaderRoute: typeof AppInvestorDeskRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/decisions': {
      id: '/app/investor/decisions'
      path: '/decisions'
      fullPath: '/app/investor/decisions'
      preLoaderRoute: typeof AppInvestorDecisionsRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/deal-rooms': {
      id: '/app/investor/deal-rooms'
      path: '/deal-rooms'
      fullPath: '/app/investor/deal-rooms'
      preLoaderRoute: typeof AppInvestorDealRoomsRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/deal-flow': {
      id: '/app/investor/deal-flow'
      path: '/deal-flow'
      fullPath: '/app/investor/deal-flow'
      preLoaderRoute: typeof AppInvestorDealFlowRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/connections': {
      id: '/app/investor/connections'
      path: '/connections'
      fullPath: '/app/investor/connections'
      preLoaderRoute: typeof AppInvestorConnectionsRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/analysis': {
      id: '/app/investor/analysis'
      path: '/analysis'
      fullPath: '/app/investor/analysis'
      preLoaderRoute: typeof AppInvestorAnalysisRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/investor/advisor': {
      id: '/app/investor/advisor'
      path: '/advisor'
      fullPath: '/app/investor/advisor'
      preLoaderRoute: typeof AppInvestorAdvisorRouteImport
      parentRoute: typeof AppInvestorRoute
    }
    '/app/deal-room/$id': {
      id: '/app/deal-room/$id'
      path: '/deal-room/$id'
      fullPath: '/app/deal-room/$id'
      preLoaderRoute: typeof AppDealRoomIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/internal/email-test': {
      id: '/api/internal/email-test'
      path: '/api/internal/email-test'
      fullPath: '/api/internal/email-test'
      preLoaderRoute: typeof ApiInternalEmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/data': {
      id: '/api/internal/data'
      path: '/api/internal/data'
      fullPath: '/api/internal/data'
      preLoaderRoute: typeof ApiInternalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/deal-room/$id_/nda': {
      id: '/app/deal-room/$id_/nda'
      path: '/deal-room/$id/nda'
      fullPath: '/app/deal-room/$id/nda'
      preLoaderRoute: typeof AppDealRoomIdNdaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppInvestorRouteChildren {
  AppInvestorAdvisorRoute: typeof AppInvestorAdvisorRoute
  AppInvestorAnalysisRoute: typeof AppInvestorAnalysisRoute
  AppInvestorConnectionsRoute: typeof AppInvestorConnectionsRoute
  AppInvestorDealFlowRoute: typeof AppInvestorDealFlowRoute
  AppInvestorDealRoomsRoute: typeof AppInvestorDealRoomsRoute
  AppInvestorDecisionsRoute: typeof AppInvestorDecisionsRoute
  AppInvestorDeskRoute: typeof AppInvestorDeskRoute
  AppInvestorDiligenceRoute: typeof AppInvestorDiligenceRoute
  AppInvestorIntakeRoute: typeof AppInvestorIntakeRoute
  AppInvestorOverviewRoute: typeof AppInvestorOverviewRoute
  AppInvestorPipelineRoute: typeof AppInvestorPipelineRoute
  AppInvestorPortfolioRoute: typeof AppInvestorPortfolioRoute
  AppInvestorProfileRoute: typeof AppInvestorProfileRoute
  AppInvestorSettingsRoute: typeof AppInvestorSettingsRoute
  AppInvestorStartupsRoute: typeof AppInvestorStartupsRoute
  AppInvestorTeamRoute: typeof AppInvestorTeamRoute
  AppInvestorIndexRoute: typeof AppInvestorIndexRoute
}

const AppInvestorRouteChildren: AppInvestorRouteChildren = {
  AppInvestorAdvisorRoute: AppInvestorAdvisorRoute,
  AppInvestorAnalysisRoute: AppInvestorAnalysisRoute,
  AppInvestorConnectionsRoute: AppInvestorConnectionsRoute,
  AppInvestorDealFlowRoute: AppInvestorDealFlowRoute,
  AppInvestorDealRoomsRoute: AppInvestorDealRoomsRoute,
  AppInvestorDecisionsRoute: AppInvestorDecisionsRoute,
  AppInvestorDeskRoute: AppInvestorDeskRoute,
  AppInvestorDiligenceRoute: AppInvestorDiligenceRoute,
  AppInvestorIntakeRoute: AppInvestorIntakeRoute,
  AppInvestorOverviewRoute: AppInvestorOverviewRoute,
  AppInvestorPipelineRoute: AppInvestorPipelineRoute,
  AppInvestorPortfolioRoute: AppInvestorPortfolioRoute,
  AppInvestorProfileRoute: AppInvestorProfileRoute,
  AppInvestorSettingsRoute: AppInvestorSettingsRoute,
  AppInvestorStartupsRoute: AppInvestorStartupsRoute,
  AppInvestorTeamRoute: AppInvestorTeamRoute,
  AppInvestorIndexRoute: AppInvestorIndexRoute,
}

const AppInvestorRouteWithChildren = AppInvestorRoute._addFileChildren(
  AppInvestorRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsDomainRoute: typeof AppSettingsDomainRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsDomainRoute: AppSettingsDomainRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppAuditRoute: typeof AppAuditRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppDealRoomsRoute: typeof AppDealRoomsRoute
  AppDeskRoute: typeof AppDeskRoute
  AppDirectoryRoute: typeof AppDirectoryRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmailRoute: typeof AppEmailRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppHomeRoute: typeof AppHomeRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInvestorRoute: typeof AppInvestorRouteWithChildren
  AppInvestorThesisRoute: typeof AppInvestorThesisRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMemberProfileRoute: typeof AppMemberProfileRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProfileBuilderRoute: typeof AppProfileBuilderRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppWallRoute: typeof AppWallRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDealRoomIdRoute: typeof AppDealRoomIdRoute
  AppMemberIndexRoute: typeof AppMemberIndexRoute
  AppDealRoomIdNdaRoute: typeof AppDealRoomIdNdaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRoute,
  AppAuditRoute: AppAuditRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppDealRoomsRoute: AppDealRoomsRoute,
  AppDeskRoute: AppDeskRoute,
  AppDirectoryRoute: AppDirectoryRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmailRoute: AppEmailRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppHomeRoute: AppHomeRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInvestorRoute: AppInvestorRouteWithChildren,
  AppInvestorThesisRoute: AppInvestorThesisRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMemberProfileRoute: AppMemberProfileRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppProfileBuilderRoute: AppProfileBuilderRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppWallRoute: AppWallRoute,
  AppIndexRoute: AppIndexRoute,
  AppDealRoomIdRoute: AppDealRoomIdRoute,
  AppMemberIndexRoute: AppMemberIndexRoute,
  AppDealRoomIdNdaRoute: AppDealRoomIdNdaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface JoinRouteChildren {
  JoinTokenRoute: typeof JoinTokenRoute
  JoinTeamTokenRoute: typeof JoinTeamTokenRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinTokenRoute: JoinTokenRoute,
  JoinTeamTokenRoute: JoinTeamTokenRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DebugRoute: DebugRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FoundersRoute: FoundersRoute,
  InvestorsRoute: InvestorsRoute,
  InviteRoute: InviteRoute,
  JoinRoute: JoinRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegistryRoute: RegistryRoute,
  ResourcesRoute: ResourcesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  WaitlistRoute: WaitlistRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAdminDataRoute: ApiAdminDataRoute,
  ApiEmailTestRoute: ApiEmailTestRoute,
  ApiEmailtestRoute: ApiEmailtestRoute,
  ApiHubspotNewsletterRoute: ApiHubspotNewsletterRoute,
  ApiHubspotSyncRoute: ApiHubspotSyncRoute,
  ApiTestAiRoute: ApiTestAiRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CvSlugRoute: CvSlugRoute,
  ISlugRoute: ISlugRoute,
  JoinInvestorTokenRoute: JoinInvestorTokenRoute,
  PSlugRoute: PSlugRoute,
  SolutionsDueDiligenceRoute: SolutionsDueDiligenceRoute,
  SolutionsFundraisingCrmRoute: SolutionsFundraisingCrmRoute,
  SolutionsInvestorPipelineRoute: SolutionsInvestorPipelineRoute,
  SolutionsRaise1mRoute: SolutionsRaise1mRoute,
  SolutionsVcDealRoomRoute: SolutionsVcDealRoomRoute,
  ToolsBurnRateRoute: ToolsBurnRateRoute,
  ToolsCapTableRoute: ToolsCapTableRoute,
  ToolsCogsRoute: ToolsCogsRoute,
  ToolsDilutionRoute: ToolsDilutionRoute,
  ToolsRunwayRoute: ToolsRunwayRoute,
  ToolsSafeNoteRoute: ToolsSafeNoteRoute,
  ToolsValuationRoute: ToolsValuationRoute,
  VerifySlugRoute: VerifySlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiInternalDataRoute: ApiInternalDataRoute,
  ApiInternalEmailTestRoute: ApiInternalEmailTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
