/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SolutionsVcDealRoomRouteImport } from './routes/solutions.vc-deal-room'
import { Route as SolutionsRaise1mRouteImport } from './routes/solutions.raise-1m'
import { Route as SolutionsInvestorPipelineRouteImport } from './routes/solutions.investor-pipeline'
import { Route as SolutionsFundraisingCrmRouteImport } from './routes/solutions.fundraising-crm'
import { Route as SolutionsDueDiligenceRouteImport } from './routes/solutions.due-diligence'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppEmailRouteImport } from './routes/app.email'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDealRoomsRouteImport } from './routes/app.deal-rooms'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAdvisorRouteImport } from './routes/app.advisor'
import { Route as AppInvestorIndexRouteImport } from './routes/app.investor.index'
import { Route as AppSettingsSecurityRouteImport } from './routes/app.settings.security'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppSettingsDomainRouteImport } from './routes/app.settings.domain'
import { Route as AppSettingsBillingRouteImport } from './routes/app.settings.billing'
import { Route as AppInvestorTeamRouteImport } from './routes/app.investor.team'
import { Route as AppInvestorStartupsRouteImport } from './routes/app.investor.startups'
import { Route as AppInvestorPortfolioRouteImport } from './routes/app.investor.portfolio'
import { Route as AppInvestorPipelineRouteImport } from './routes/app.investor.pipeline'
import { Route as AppInvestorDiligenceRouteImport } from './routes/app.investor.diligence'
import { Route as AppInvestorDecisionsRouteImport } from './routes/app.investor.decisions'
import { Route as AppInvestorDealRoomsRouteImport } from './routes/app.investor.deal-rooms'
import { Route as AppInvestorDealFlowRouteImport } from './routes/app.investor.deal-flow'
import { Route as AppInvestorAnalysisRouteImport } from './routes/app.investor.analysis'
import { Route as AppDealRoomIdRouteImport } from './routes/app.deal-room.$id'
import { Route as AppDealRoomIdNdaRouteImport } from './routes/app.deal-room.$id_.nda'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SolutionsVcDealRoomRoute = SolutionsVcDealRoomRouteImport.update({
  id: '/solutions/vc-deal-room',
  path: '/solutions/vc-deal-room',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRaise1mRoute = SolutionsRaise1mRouteImport.update({
  id: '/solutions/raise-1m',
  path: '/solutions/raise-1m',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsInvestorPipelineRoute =
  SolutionsInvestorPipelineRouteImport.update({
    id: '/solutions/investor-pipeline',
    path: '/solutions/investor-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsFundraisingCrmRoute = SolutionsFundraisingCrmRouteImport.update({
  id: '/solutions/fundraising-crm',
  path: '/solutions/fundraising-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsDueDiligenceRoute = SolutionsDueDiligenceRouteImport.update({
  id: '/solutions/due-diligence',
  path: '/solutions/due-diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDealRoomsRoute = AppDealRoomsRouteImport.update({
  id: '/deal-rooms',
  path: '/deal-rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorIndexRoute = AppInvestorIndexRouteImport.update({
  id: '/investor/',
  path: '/investor/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsDomainRoute = AppSettingsDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInvestorTeamRoute = AppInvestorTeamRouteImport.update({
  id: '/investor/team',
  path: '/investor/team',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorStartupsRoute = AppInvestorStartupsRouteImport.update({
  id: '/investor/startups',
  path: '/investor/startups',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorPortfolioRoute = AppInvestorPortfolioRouteImport.update({
  id: '/investor/portfolio',
  path: '/investor/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorPipelineRoute = AppInvestorPipelineRouteImport.update({
  id: '/investor/pipeline',
  path: '/investor/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorDiligenceRoute = AppInvestorDiligenceRouteImport.update({
  id: '/investor/diligence',
  path: '/investor/diligence',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorDecisionsRoute = AppInvestorDecisionsRouteImport.update({
  id: '/investor/decisions',
  path: '/investor/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorDealRoomsRoute = AppInvestorDealRoomsRouteImport.update({
  id: '/investor/deal-rooms',
  path: '/investor/deal-rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorDealFlowRoute = AppInvestorDealFlowRouteImport.update({
  id: '/investor/deal-flow',
  path: '/investor/deal-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorAnalysisRoute = AppInvestorAnalysisRouteImport.update({
  id: '/investor/analysis',
  path: '/investor/analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppDealRoomIdRoute = AppDealRoomIdRouteImport.update({
  id: '/deal-room/$id',
  path: '/deal-room/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDealRoomIdNdaRoute = AppDealRoomIdNdaRouteImport.update({
  id: '/deal-room/$id_/nda',
  path: '/deal-room/$id/nda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/audit': typeof AppAuditRoute
  '/app/deal-rooms': typeof AppDealRoomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/join/$token': typeof JoinTokenRoute
  '/solutions/due-diligence': typeof SolutionsDueDiligenceRoute
  '/solutions/fundraising-crm': typeof SolutionsFundraisingCrmRoute
  '/solutions/investor-pipeline': typeof SolutionsInvestorPipelineRoute
  '/solutions/raise-1m': typeof SolutionsRaise1mRoute
  '/solutions/vc-deal-room': typeof SolutionsVcDealRoomRoute
  '/app/': typeof AppIndexRoute
  '/app/deal-room/$id': typeof AppDealRoomIdRoute
  '/app/investor/analysis': typeof AppInvestorAnalysisRoute
  '/app/investor/deal-flow': typeof AppInvestorDealFlowRoute
  '/app/investor/deal-rooms': typeof AppInvestorDealRoomsRoute
  '/app/investor/decisions': typeof AppInvestorDecisionsRoute
  '/app/investor/diligence': typeof AppInvestorDiligenceRoute
  '/app/investor/pipeline': typeof AppInvestorPipelineRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/startups': typeof AppInvestorStartupsRoute
  '/app/investor/team': typeof AppInvestorTeamRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/domain': typeof AppSettingsDomainRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/deal-room/$id/nda': typeof AppDealRoomIdNdaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/audit': typeof AppAuditRoute
  '/app/deal-rooms': typeof AppDealRoomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/join/$token': typeof JoinTokenRoute
  '/solutions/due-diligence': typeof SolutionsDueDiligenceRoute
  '/solutions/fundraising-crm': typeof SolutionsFundraisingCrmRoute
  '/solutions/investor-pipeline': typeof SolutionsInvestorPipelineRoute
  '/solutions/raise-1m': typeof SolutionsRaise1mRoute
  '/solutions/vc-deal-room': typeof SolutionsVcDealRoomRoute
  '/app': typeof AppIndexRoute
  '/app/deal-room/$id': typeof AppDealRoomIdRoute
  '/app/investor/analysis': typeof AppInvestorAnalysisRoute
  '/app/investor/deal-flow': typeof AppInvestorDealFlowRoute
  '/app/investor/deal-rooms': typeof AppInvestorDealRoomsRoute
  '/app/investor/decisions': typeof AppInvestorDecisionsRoute
  '/app/investor/diligence': typeof AppInvestorDiligenceRoute
  '/app/investor/pipeline': typeof AppInvestorPipelineRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/startups': typeof AppInvestorStartupsRoute
  '/app/investor/team': typeof AppInvestorTeamRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/domain': typeof AppSettingsDomainRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/investor': typeof AppInvestorIndexRoute
  '/app/deal-room/$id/nda': typeof AppDealRoomIdNdaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/audit': typeof AppAuditRoute
  '/app/deal-rooms': typeof AppDealRoomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email': typeof AppEmailRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/join/$token': typeof JoinTokenRoute
  '/solutions/due-diligence': typeof SolutionsDueDiligenceRoute
  '/solutions/fundraising-crm': typeof SolutionsFundraisingCrmRoute
  '/solutions/investor-pipeline': typeof SolutionsInvestorPipelineRoute
  '/solutions/raise-1m': typeof SolutionsRaise1mRoute
  '/solutions/vc-deal-room': typeof SolutionsVcDealRoomRoute
  '/app/': typeof AppIndexRoute
  '/app/deal-room/$id': typeof AppDealRoomIdRoute
  '/app/investor/analysis': typeof AppInvestorAnalysisRoute
  '/app/investor/deal-flow': typeof AppInvestorDealFlowRoute
  '/app/investor/deal-rooms': typeof AppInvestorDealRoomsRoute
  '/app/investor/decisions': typeof AppInvestorDecisionsRoute
  '/app/investor/diligence': typeof AppInvestorDiligenceRoute
  '/app/investor/pipeline': typeof AppInvestorPipelineRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/startups': typeof AppInvestorStartupsRoute
  '/app/investor/team': typeof AppInvestorTeamRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/domain': typeof AppSettingsDomainRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/deal-room/$id_/nda': typeof AppDealRoomIdNdaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/debug'
    | '/forgot-password'
    | '/founders'
    | '/investors'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/app/advisor'
    | '/app/audit'
    | '/app/deal-rooms'
    | '/app/documents'
    | '/app/email'
    | '/app/leads'
    | '/app/meetings'
    | '/app/messages'
    | '/app/notifications'
    | '/app/pipeline'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/join/$token'
    | '/solutions/due-diligence'
    | '/solutions/fundraising-crm'
    | '/solutions/investor-pipeline'
    | '/solutions/raise-1m'
    | '/solutions/vc-deal-room'
    | '/app/'
    | '/app/deal-room/$id'
    | '/app/investor/analysis'
    | '/app/investor/deal-flow'
    | '/app/investor/deal-rooms'
    | '/app/investor/decisions'
    | '/app/investor/diligence'
    | '/app/investor/pipeline'
    | '/app/investor/portfolio'
    | '/app/investor/startups'
    | '/app/investor/team'
    | '/app/settings/billing'
    | '/app/settings/domain'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/app/investor/'
    | '/app/deal-room/$id/nda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/debug'
    | '/forgot-password'
    | '/founders'
    | '/investors'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/app/advisor'
    | '/app/audit'
    | '/app/deal-rooms'
    | '/app/documents'
    | '/app/email'
    | '/app/leads'
    | '/app/meetings'
    | '/app/messages'
    | '/app/notifications'
    | '/app/pipeline'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/join/$token'
    | '/solutions/due-diligence'
    | '/solutions/fundraising-crm'
    | '/solutions/investor-pipeline'
    | '/solutions/raise-1m'
    | '/solutions/vc-deal-room'
    | '/app'
    | '/app/deal-room/$id'
    | '/app/investor/analysis'
    | '/app/investor/deal-flow'
    | '/app/investor/deal-rooms'
    | '/app/investor/decisions'
    | '/app/investor/diligence'
    | '/app/investor/pipeline'
    | '/app/investor/portfolio'
    | '/app/investor/startups'
    | '/app/investor/team'
    | '/app/settings/billing'
    | '/app/settings/domain'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/app/investor'
    | '/app/deal-room/$id/nda'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/debug'
    | '/forgot-password'
    | '/founders'
    | '/investors'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/app/advisor'
    | '/app/audit'
    | '/app/deal-rooms'
    | '/app/documents'
    | '/app/email'
    | '/app/leads'
    | '/app/meetings'
    | '/app/messages'
    | '/app/notifications'
    | '/app/pipeline'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/join/$token'
    | '/solutions/due-diligence'
    | '/solutions/fundraising-crm'
    | '/solutions/investor-pipeline'
    | '/solutions/raise-1m'
    | '/solutions/vc-deal-room'
    | '/app/'
    | '/app/deal-room/$id'
    | '/app/investor/analysis'
    | '/app/investor/deal-flow'
    | '/app/investor/deal-rooms'
    | '/app/investor/decisions'
    | '/app/investor/diligence'
    | '/app/investor/pipeline'
    | '/app/investor/portfolio'
    | '/app/investor/startups'
    | '/app/investor/team'
    | '/app/settings/billing'
    | '/app/settings/domain'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/app/investor/'
    | '/app/deal-room/$id_/nda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  DebugRoute: typeof DebugRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FoundersRoute: typeof FoundersRoute
  InvestorsRoute: typeof InvestorsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  JoinTokenRoute: typeof JoinTokenRoute
  SolutionsDueDiligenceRoute: typeof SolutionsDueDiligenceRoute
  SolutionsFundraisingCrmRoute: typeof SolutionsFundraisingCrmRoute
  SolutionsInvestorPipelineRoute: typeof SolutionsInvestorPipelineRoute
  SolutionsRaise1mRoute: typeof SolutionsRaise1mRoute
  SolutionsVcDealRoomRoute: typeof SolutionsVcDealRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/solutions/vc-deal-room': {
      id: '/solutions/vc-deal-room'
      path: '/solutions/vc-deal-room'
      fullPath: '/solutions/vc-deal-room'
      preLoaderRoute: typeof SolutionsVcDealRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/raise-1m': {
      id: '/solutions/raise-1m'
      path: '/solutions/raise-1m'
      fullPath: '/solutions/raise-1m'
      preLoaderRoute: typeof SolutionsRaise1mRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/investor-pipeline': {
      id: '/solutions/investor-pipeline'
      path: '/solutions/investor-pipeline'
      fullPath: '/solutions/investor-pipeline'
      preLoaderRoute: typeof SolutionsInvestorPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/fundraising-crm': {
      id: '/solutions/fundraising-crm'
      path: '/solutions/fundraising-crm'
      fullPath: '/solutions/fundraising-crm'
      preLoaderRoute: typeof SolutionsFundraisingCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/due-diligence': {
      id: '/solutions/due-diligence'
      path: '/solutions/due-diligence'
      fullPath: '/solutions/due-diligence'
      preLoaderRoute: typeof SolutionsDueDiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email': {
      id: '/app/email'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deal-rooms': {
      id: '/app/deal-rooms'
      path: '/deal-rooms'
      fullPath: '/app/deal-rooms'
      preLoaderRoute: typeof AppDealRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisor': {
      id: '/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/': {
      id: '/app/investor/'
      path: '/investor'
      fullPath: '/app/investor/'
      preLoaderRoute: typeof AppInvestorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/domain': {
      id: '/app/settings/domain'
      path: '/domain'
      fullPath: '/app/settings/domain'
      preLoaderRoute: typeof AppSettingsDomainRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/investor/team': {
      id: '/app/investor/team'
      path: '/investor/team'
      fullPath: '/app/investor/team'
      preLoaderRoute: typeof AppInvestorTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/startups': {
      id: '/app/investor/startups'
      path: '/investor/startups'
      fullPath: '/app/investor/startups'
      preLoaderRoute: typeof AppInvestorStartupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/portfolio': {
      id: '/app/investor/portfolio'
      path: '/investor/portfolio'
      fullPath: '/app/investor/portfolio'
      preLoaderRoute: typeof AppInvestorPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/pipeline': {
      id: '/app/investor/pipeline'
      path: '/investor/pipeline'
      fullPath: '/app/investor/pipeline'
      preLoaderRoute: typeof AppInvestorPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/diligence': {
      id: '/app/investor/diligence'
      path: '/investor/diligence'
      fullPath: '/app/investor/diligence'
      preLoaderRoute: typeof AppInvestorDiligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/decisions': {
      id: '/app/investor/decisions'
      path: '/investor/decisions'
      fullPath: '/app/investor/decisions'
      preLoaderRoute: typeof AppInvestorDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/deal-rooms': {
      id: '/app/investor/deal-rooms'
      path: '/investor/deal-rooms'
      fullPath: '/app/investor/deal-rooms'
      preLoaderRoute: typeof AppInvestorDealRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/deal-flow': {
      id: '/app/investor/deal-flow'
      path: '/investor/deal-flow'
      fullPath: '/app/investor/deal-flow'
      preLoaderRoute: typeof AppInvestorDealFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/analysis': {
      id: '/app/investor/analysis'
      path: '/investor/analysis'
      fullPath: '/app/investor/analysis'
      preLoaderRoute: typeof AppInvestorAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deal-room/$id': {
      id: '/app/deal-room/$id'
      path: '/deal-room/$id'
      fullPath: '/app/deal-room/$id'
      preLoaderRoute: typeof AppDealRoomIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deal-room/$id_/nda': {
      id: '/app/deal-room/$id_/nda'
      path: '/deal-room/$id/nda'
      fullPath: '/app/deal-room/$id/nda'
      preLoaderRoute: typeof AppDealRoomIdNdaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsDomainRoute: typeof AppSettingsDomainRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsDomainRoute: AppSettingsDomainRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDealRoomsRoute: typeof AppDealRoomsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmailRoute: typeof AppEmailRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDealRoomIdRoute: typeof AppDealRoomIdRoute
  AppInvestorAnalysisRoute: typeof AppInvestorAnalysisRoute
  AppInvestorDealFlowRoute: typeof AppInvestorDealFlowRoute
  AppInvestorDealRoomsRoute: typeof AppInvestorDealRoomsRoute
  AppInvestorDecisionsRoute: typeof AppInvestorDecisionsRoute
  AppInvestorDiligenceRoute: typeof AppInvestorDiligenceRoute
  AppInvestorPipelineRoute: typeof AppInvestorPipelineRoute
  AppInvestorPortfolioRoute: typeof AppInvestorPortfolioRoute
  AppInvestorStartupsRoute: typeof AppInvestorStartupsRoute
  AppInvestorTeamRoute: typeof AppInvestorTeamRoute
  AppInvestorIndexRoute: typeof AppInvestorIndexRoute
  AppDealRoomIdNdaRoute: typeof AppDealRoomIdNdaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRoute,
  AppAuditRoute: AppAuditRoute,
  AppDealRoomsRoute: AppDealRoomsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmailRoute: AppEmailRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppDealRoomIdRoute: AppDealRoomIdRoute,
  AppInvestorAnalysisRoute: AppInvestorAnalysisRoute,
  AppInvestorDealFlowRoute: AppInvestorDealFlowRoute,
  AppInvestorDealRoomsRoute: AppInvestorDealRoomsRoute,
  AppInvestorDecisionsRoute: AppInvestorDecisionsRoute,
  AppInvestorDiligenceRoute: AppInvestorDiligenceRoute,
  AppInvestorPipelineRoute: AppInvestorPipelineRoute,
  AppInvestorPortfolioRoute: AppInvestorPortfolioRoute,
  AppInvestorStartupsRoute: AppInvestorStartupsRoute,
  AppInvestorTeamRoute: AppInvestorTeamRoute,
  AppInvestorIndexRoute: AppInvestorIndexRoute,
  AppDealRoomIdNdaRoute: AppDealRoomIdNdaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  DebugRoute: DebugRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FoundersRoute: FoundersRoute,
  InvestorsRoute: InvestorsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  JoinTokenRoute: JoinTokenRoute,
  SolutionsDueDiligenceRoute: SolutionsDueDiligenceRoute,
  SolutionsFundraisingCrmRoute: SolutionsFundraisingCrmRoute,
  SolutionsInvestorPipelineRoute: SolutionsInvestorPipelineRoute,
  SolutionsRaise1mRoute: SolutionsRaise1mRoute,
  SolutionsVcDealRoomRoute: SolutionsVcDealRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
